verbose: false
instrumentation:
    root: .
    extensions:
      - .es6
    excludes:
      - app.es6
    include-all-sources: true
    es-modules: true
reporting:
    reports:
        - html
    dir: ./coverage